global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: pulsenotify_api
    static_configs:
      - targets: ['172.28.51.39:8000']

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
